### ISSUE TITLE
windows 0.9.0 errors

### ISSUE THREAD

**Issue by bluelemonade** [bakercp/ofxPS3EyeGrabber#14]
hi,

I tried to compile the example_PS3_multicam project  with 0.9.0 an vs2015. 

I got following errors:
![screenshot 294](https://cloud.githubusercontent.com/assets/245589/15604365/444b7620-2400-11e6-8214-085c2da92389.png)

when I make a new project with your examples, I got a lot of errors. 
![screenshot 295](https://cloud.githubusercontent.com/assets/245589/15604439/ad3fac64-2400-11e6-9a89-96d07f02716e.png)

I don't know where to start to fix this...

regards

**Comment by bakercp** [comment]
Windows support is still being developed see this existing issue https://github.com/bakercp/ofxPS3EyeGrabber/issues/4
