### ISSUE TITLE
Camera dropping frames on macOS

### ISSUE THREAD

**Issue by Rashed97** [bakercp/ofxPS3EyeGrabber#16]
Hi,

I'm using this on macOS Sierra 10.12.1 and the camera seems to be dropping a few frames every second. Just wondering is there 1) any history of this happening or 2) any way to debug it to figure out what's causing the dropped frames?

Thanks!

**Comment by bakercp** [comment]
What fps / resolution are you using?

**Comment by fishkingsin** [comment]
I have the same issue 
with 640x480 60 fps

**Comment by bakercp** [comment]
If you change this line to:

https://github.com/bakercp/ofxPS3EyeGrabber/blob/master/libs/ps3eye/src/USBManager.cpp#L291

`frame_add(DISCARD_PACKET, NULL, 0);`

Does it fix it?

Based on this:

https://github.com/inspirit/PS3EYEDriver/commit/5267d7589fc9887b4b840198b2ad121ec210895e#diff-d71bc9bc61e2ffd7e1fe7ad0fe951b00L769

**Comment by bakercp** [comment]
The master branch if tested and working with significant improvements to speed and many other bugs.  Please test and reopen this issue if it doesn't work.
