### ISSUE TITLE
Don't know how to convert 'std::vector<std::shared_ptr<ofVideoGrabber>> grabbers' ?

### ISSUE THREAD

**Issue by LuZhouheng** [bakercp/ofxPS3EyeGrabber#17]
Hi, @bakercp and all developers.

I'm wondering how to convert this pointer in your `example_advanced_multicam` ? 

`std::vector<std::shared_ptr<ofVideoGrabber>> grabbers;`

I want to convert it to some kind of this function: ofPixels(), some functions in ofxCv & ofxOpenCv, like: ofCvColorImage() but failed. I have bee google that and find some example on Github, but still, can not solve this stuff.

Is there any way to convert `shared_ptr` to be used in ofxOpenCv?

Thanks for your help.

**Comment by bakercp** [comment]
It's a shared pointer. To call a function on a pointer, you use the `->`
operator.

**Comment by bakercp** [comment]
http://stackoverflow.com/questions/1238613/what-is-the-difference-between-the-dot-operator-and-in-c

http://stackoverflow.com/questions/221346/what-can-i-use-instead-of-the-arrow-operator

**Comment by LuZhouheng** [comment]
Thanks very much. It works.
