### ISSUE TITLE
not receiving any frames due to payload error

### ISSUE THREAD

**Issue by ptigas** [bakercp/ofxPS3EyeGrabber#18]
Hi,

I'm not receiving any new frames from the camera. I've been using https://github.com/inspirit/PS3EYEDriver with no problems, but it seems the modified version is not working for me.

After a bit of debugging it seems that I get payload errors in `pkt_scan`. Any ideas?

## 

FPS: default 60
Resolution: default 640x480

## Debug output
```
...
length:16384, actual_length:16384
length:16384, actual_length:8268
length:16384, actual_length:12
payload error
length:16384, actual_length:16384
length:16384, actual_length:4672
length:16384, actual_length:12
payload error
length:16384, actual_length:16384
length:16384, actual_length:3648
length:16384, actual_length:12
payload error
length:16384, actual_length:16384
length:16384, actual_length:16384
length:16384, actual_length:10316
length:16384, actual_length:12
payload error
length:16384, actual_length:16384
length:16384, actual_length:3132
length:16384, actual_length:12
payload error
length:16384, actual_length:16384
length:16384, actual_length:4172
length:16384, actual_length:12
payload error
...
```

**Comment by bakercp** [comment]
The master branch if tested and working with significant improvements to speed and many other bugs.  Please test and reopen this issue if it doesn't work.
