### ISSUE TITLE
Can't get master branch to compile on OS X

### ISSUE THREAD

**Issue by crosswick** [bakercp/ofxPS3EyeGrabber#19]
Hi! Looking forward to getting this to work, I love these cameras.

The stable branch does compile with the 0.9.8 release of openFrameworks, albeit with some blue lines visible in the video.

As far as compiling the master branch, I'm getting the following error:
_GL/glew.h file not found in ofConstants.h_

My method is:
- downloading master zips of openFrameworks and this addon, unzipping and removing the "-master" at the end of the folder name;
- putting the ofxPS3EyeGrabber folder in the addons folder of the openFrameworks folder;
- putting the projectGenerator (from the 0.9.8 release) in the apps/projectGenerator folder, running it and setting the openFrameworks path to the openFrameworks folder;
- with it, creating a new project with the ofxPS3EyeGrabber, ofxKinect and ofxOpenCv addons, opening up the project generated in Xcode 8.2.1;
- in Xcode, deleting the three files in the src folder, moving them to the trash;
- from the openFrameworks/addons/ofxPS3EyeGrabber/example_advanced_settings/src folder, dragging the three files (main.cpp, ofApp.cpp and ofApp.h) into the src folder in Xcode;
- Run the Xcode project, which yields the error mentioned above: GL/glew.h file not found

I have searched for glew.h, which does seem to be in the 0.9.8 release; following the same method with that yields the error ofJson.h file not found in ofxPS3EyeGrabber.h.

Any help greatly appreciated!

**Comment by bakercp** [comment]
The master branch if tested and working with significant improvements to speed and many other bugs.  Please test and reopen this issue if it doesn't work.

**Comment by crosswick** [comment]
Ah great, will do so soon. Thank you!

Op 18 jan. 2018 22:49 schreef "Christopher Baker" <notifications@github.com

**Comment by crosswick** [comment]
Hi! I just repeated the steps above with the latest master branch, and I'm still getting the error:

/Users/steven/Projects/ofxPS3EyeGrabber/openFrameworks/libs/openFrameworks/utils/ofConstants.h:183:11: 'GL/glew.h' file not found
