### ISSUE TITLE
ofJson.h not found

### ISSUE THREAD

**Issue by VVZen** [bakercp/ofxPS3EyeGrabber#20]
Hi,
I'm trying to compile this addon on **macOS El Capitan** using _make_.

The first error that I encounter is that the `ofJson.h` file is not found. I made a quick `grep` in my openframeworks folder and this addon seems to be the only one including.
I then replace the two occurrences of `ofJson` to `ofxJSON` and I'm no longer getting the error. As a bonus, I got another one:

```
unknown type name 'ofEventListener'; did you mean
      'Poco::XML::EventListener'?
```

Again, I grepped for `ofEventListener` inside my events folder (_libs/openFrameworks/events_) and I didn't find anything, while when searching the online git repo I did found the definition of this Class.

My two questions for **anybody** that is reading are : 

• is ofJson.h deprecated? 
• is ofEventListener present only in some new experimental branch or is it something from the past? 

Thanks

**Comment by bakercp** [comment]
Please refer to the README.md

https://github.com/bakercp/ofxPS3EyeGrabber#compatibility

**Comment by VVZen** [comment]
@bakercp thanks for your super-quick answer! I overlooked it. Thank you so much for what you do!

**Comment by bakercp** [comment]
@VVZen My pleasure! Good luck w/ your project.
