### ISSUE TITLE
'GL/glew.h' file not found

### ISSUE THREAD

**Issue by crosswick** [bakercp/ofxPS3EyeGrabber#21]
Hi! I can't re-open issue #19 like you requested so I'm opening this new one to reference it.

I've tested again with the latest master branch and am still getting the same error as before:

/openFrameworks/libs/openFrameworks/utils/ofConstants.h:183:11: 'GL/glew.h' file not found

Looking forward to checking out the improvements you mentioned! Thanks again for your help.

**Comment by bakercp** [comment]
Hm.  I'm literally using it right now and it sounds like this is an issue with your openFrameworks setup, not this addon.  Currently the addon is passing tests on Linux, Mac and VS, MSYS on Windows.

I'd double check your openFrameworks setup, regenerate project files, make sure you're using the master branch and have installed everything correctly.

**Comment by crosswick** [comment]
Thanks for the fast reply. I don't really know how it could be an issue with my OF setup, seen as I downloaded everything fresh... again, this is the recipe I'm following:

- downloading master zips of openFrameworks and this addon, unzipping and removing the "-master" at the end of the folder name;
- putting the ofxPS3EyeGrabber folder in the addons folder of the openFrameworks folder;
- putting the projectGenerator (from the 0.9.8 release) in the apps/projectGenerator folder, running it and setting the openFrameworks path to the openFrameworks folder;
- with it, creating a new project with the ofxPS3EyeGrabber, ofxKinect and ofxOpenCv addons, opening up the project generated in Xcode 8.2.1;
- in Xcode, deleting the three files in the src folder, moving them to the trash;
- from the openFrameworks/addons/ofxPS3EyeGrabber/example_advanced_settings/src folder, dragging the three files (main.cpp, ofApp.cpp and ofApp.h) into the src folder in Xcode;
- Run the Xcode project, which yields the error mentioned above: GL/glew.h file not found

**Comment by crosswick** [comment]
Hmm getting the same error now with the most basic 'firstSketch' example from http://openframeworks.cc/setup/xcode/, so it must be something with my OF setup indeed. Will investigate further and come back once it's sorted

**Comment by bakercp** [comment]
If you install from the master branch you either need to get the nightly build:

http://ci.openframeworks.cc/versions/nightly/of_v20180202_osx_nightly.zip

Or you need to follow these instructions:

https://github.com/openframeworks/openFrameworks/blob/master/INSTALL_FROM_GITHUB.md

The nightly build has all of the included libraries.  The INSTALL_FROM_GITHUB tells you how to do it yourself.

**Comment by crosswick** [comment]
Ah ok thanks, will try the nightly build now first.

In the mean time I found this page detailing the glew.h issue apparently, at the bottom:
https://forum.openframeworks.cc/t/error-message-gl-glew-h-file-not-found/8716/9

**Comment by bakercp** [comment]
Yep, that's in the instructions:

https://github.com/openframeworks/openFrameworks/blob/master/INSTALL_FROM_GITHUB.md

**Comment by crosswick** [comment]
Ah my bad. I assumed downloading a master .zip from github was the same as downloading a release version from http://openframeworks.cc/download/

**Comment by bakercp** [comment]
Nope.  Keep me posted :)

**Comment by crosswick** [comment]
![image](https://user-images.githubusercontent.com/526402/35756020-e59f020e-0869-11e8-90c7-4cc3f7e03f33.png)
