### ISSUE TITLE
Videos recording

### ISSUE THREAD

**Issue by PhuDoTuong** [bakercp/ofxPS3EyeGrabber#22]
Hi @bakercp, thank you for your amazing contribution. I would like to create a GUI button to record videos from 2 PS3 cameras. How could I synchronize between "App fps" and "Cam fps".

**Comment by bakercp** [comment]
Hi there, I don't understand your question.

**Comment by PhuDoTuong** [comment]
Hello @bakercp, sorry for my late response and unclear question. "App FPS" and "Real FPS" is illustrated on following figure:
![image](https://user-images.githubusercontent.com/73333393/103474428-50de0600-4dd6-11eb-844d-fdf93088529e.png)
I wonder that if I create a GUI button (using ofxGUI) to record videos, I won't capture consecutive frames.

**Comment by moebiussurfing** [comment]
you can try using the lower fps on the recorder

**Comment by bakercp** [comment]
Closing this issue and moved my response to the forum as this isn't an bug with the addon.

https://forum.openframeworks.cc/t/videos-recording-using-ofxps3eyegrabber/36934/3

**Comment by bakercp** [comment]
The slow-mo example shows how to deal with frame rates greater than your screen refresh rate 

https://github.com/bakercp/ofxPS3EyeGrabber/blob/master/example_advanced_slow_mo/src/ofApp.cpp
