### ISSUE TITLE
Update to use native YUV pixels.

### ISSUE THREAD

**Issue by bakercp** [bakercp/ofxPS3EyeGrabber#5]
This requires this PR:

https://github.com/openframeworks/openFrameworks/pull/2190#issuecomment-54509435

**Comment by bakercp** [comment]
@arturoc - I have been trying to get this to work -- taking the raw YUV422 from the PS3Eye to display in natively format on the GPU with the recent updates to ofPixel ... but I'm not able to get it to show up correctly.

Basically I allocate my internal pixels [here](https://github.com/bakercp/ofxPS3EyeGrabber/blob/develop-linux/src/ofxPS3EyeGrabber.cpp#L141-L143
) using something like:

```c++
                _pixels.allocate(_cam->getWidth(),
                                 _cam->getHeight(),
								 OF_PIXELS_UYVY);
```

Then when I need to update the pixels, I'm attempting to set them like this:

```c++
			_pixels.setFromAlignedPixels(_cam->getLastFramePointer(),
										 _cam->getWidth(),
										 _cam->getHeight(),
										 4,
										 _cam->getRowBytes());
```
or 
```c++
			_pixels.setFromPixels(_cam->getLastFramePointer(),
								  _cam->getWidth(),
								  _cam->getHeight(),
								  OF_PIXELS_UYVY);
```

but nothing seems to work ...

Does the current version of ofPixels allow pixels to be set using YUV422 aligned pixels?  Perhaps I'm just missing something?

**Comment by arturoc** [comment]
i haven't tested setFromAlignedPixels with any yuv format but setFromPixels should work, unless you really need to have a stride.

can you post an image of what you are getting?

**Comment by arturoc** [comment]
also the fastest if you can somehow tell the driver to keep the last frame around until next frame is to use `setFromExternalPixels` since that wraps the memory that you get from the driver without making any copy.

**Comment by bakercp** [comment]
Hey @arturoc so now I'm allocating my pixels like so:

```c++
_pixels.allocate(_cam->getWidth(),
                 _cam->getHeight(),
                OF_PIXELS_YUY2);
```

then setting my pixels like this:

```c++
_pixels.setFromExternalPixels(_cam->getLastFramePointer(),
						  _cam->getWidth(),
						  _cam->getHeight(),
						  OF_PIXELS_YUY2);
```

Then before drawing to the screen, I'm uploading those pixels to an ofTexture like this ...

```c++
_texture.loadData(_pixels);
```

After loading the texture data, I checked the internal gl format and it is `GL_LUMINANCE_ALPHA` (?) which seems to match the outcome of a switch statement inside `ofTexture` when loading `OF_PIXELS_YUY2`.

But my video output is this:

![screenshot_10_7_15__9_21_pm](https://cloud.githubusercontent.com/assets/300484/10356272/0aab971e-6d3b-11e5-8218-e0c6c54d7068.png)

Note the grayscale and 

When I convert the YUV to RGB manually and set the pixels that way I get something that looks like this ...

![update_to_use_native_yuv_pixels__ _issue__5_ _bakercp_ofxps3eyegrabber](https://cloud.githubusercontent.com/assets/300484/10356336/b1f06996-6d3b-11e5-83e1-b4fb3386c6e8.png)

Perhaps my expectations are incorrect, but should I be seeing a color image when I draw the YUV422 texture directly?  Or is there another shader step missing to convert the YUV422 texture to an RGB colorspace for display?

Also ... in the process of using `setFromExternalPixels` I noted that it was the only one of the `set` functions that did not take a `const PixelType* pointer` ... is there a reason for this?  It seems like external pixels pointers should be read only ... or at least have the option of setting them without casting away const?

	void setFromExternalPixels(PixelType * newPixels,int w, int h, int channels);
	void setFromExternalPixels(PixelType * newPixels,int w, int h, ofPixelFormat pixelFormat);

thanks for your help on this ...

**Comment by arturoc** [comment]
That's expected, a yuv image has more than one plane and needs more than one texture to be drawn, there's no native type for yuv textures in openGL so there's no way either to specify through 1 ofTexture that the content is YUV. When you pass a YUV ofPixels into an ofTexture it allocates as 1 channel and draws only the luminance, the Y which is the most understandable representation.

ofPixels has a getPlanes() function that can return the different planes in a YUV image so you can create several textures out of it and then pass them to the shader that does the color conversion.

The correct (and the easiest) way to do this is to make your videograbber class implement ofBaseVideoGrabber, create an ofPixels with the correct pixel format and return it through getPixels.

then you can do:

```cpp
//.h
ofVideoGrabber grabber;

//setup
grabber.setGrabber(std::make_shared<ofxPS3EyeyGrabber>());
...
```

from there on, you just use ofVideoGrabber, which takes care of doing the right thing with the yuv planes. you can of course create the shared_ptr before hand in case you need to do some extra initialization.

by the way if you use `setFromExternalPixels` you don't need to call allocate at all.

**Comment by arturoc** [comment]
also if you call `setPixelFormat(OF_PIXELS_NATIVE)` in your class it should do the right thing, ie: choose the native format from the camera that requires no colorspace conversion in the cpu.

**Comment by bakercp** [comment]
@arturoc This makes a lot of sense now.  Thanks for the clarification.  I knew I must be missing something.  I'll set it up as you suggest and let you know if I run into any issues.  Thanks!

**Comment by bakercp** [comment]
Done.  This is working really nicely now.  Thanks for the help @arturoc .

**Comment by lewisou** [comment]
@bakercp @arturoc I try to draw YUV420p images on the screen. But I get a grey scaled video with no color. Below is some of my code, could you please help? 

**class RtspVideoGrabber : public ofBaseVideoGrabber**
`// YUV data in the data array`
`mYpixels.setFromExternalPixels(data[0], width, height, OF_PIXELS_Y);`
`mUpixels.setFromExternalPixels(data[1], width, height, OF_PIXELS_U);`
`mVpixels.setFromExternalPixels(data[2], width, height, OF_PIXELS_V);`

`mPixels.allocate(width, height, OF_PIXELS_I420);`
`mPixels.getPlane(0) = mYpixels;`
`mPixels.getPlane(1) = mUpixels;`
`mPixels.getPlane(2) = mVpixels;`
        
`const ofPixels& RtspVideoGrabber::getPixels() const {`
`    return mPixels;`
`}`

`ofPixelFormat RtspVideoGrabber::getPixelFormat() const {`
`    return OF_PIXELS_NATIVE;`
`}`

**ofApp**
`void ofApp::setup() {`
`mVideoGrabber.setGrabber(std::make_shared<RtspVideoGrabber>(url));`
`mVideoGrabber.initGrabber(1920, 1080);`
`}`
`void ofApp::update() {`
`    mVideoGrabber.update();`
`}`

`void ofApp::draw(){
`    if(mVideoGrabber.getWidth() > 0) {
`        mVideoGrabber.draw(0, 0, mVideoGrabber.getWidth() / 2, mVideoGrabber.getHeight() / 2);
`    }
`}`

**Comment by bakercp** [comment]
What window type / GL / OF / platform version are you using?

**Comment by lewisou** [comment]
I run the app on Android (should be glew? ).  I checked out Openframework from GitHub.

version: c274c7fb51b4ae0552cd4cdb00475458aeeb610a

**Comment by lewisou** [comment]
@bakercp I just tried to run the app on OSX, also grey scale. Maybe I missed something.

**Comment by bakercp** [comment]
(Edited because it was wrong)

**Comment by bakercp** [comment]
Ultimately the shader looks at the pixel type of the pixels / texture.

https://github.com/openframeworks/openFrameworks/blob/58e47e329d4a2717b5211755a1cb2e65a1a5e1a9/libs/openFrameworks/gl/ofGLProgrammableRenderer.cpp#L2344-L2346

I would do some tests with a known good ofPixels filled with I420 formatted data and see if it is rendered correctly via the shader.  Also make sure you are using the programmable renderer. This might require you to set your GL type to 3+. I don't recall if the fixed pipeline is still default or not in 0.10.0.

**Comment by lewisou** [comment]
I have changed my code as below. Still grey scale. I have added pixelFormat == OF_PIXELS_I420 to the else if section.

I don't find any ofPixels construction code in your ofxPS3EyeGrabber.cpp. Do you know where the source code of _frameChannel is ?

`//---------------------------------------------------------------------------`
`bool RtspVideoGrabber::setPixelFormat(ofPixelFormat pixelFormat) {`
 `   if (pixelFormat == OF_PIXELS_NATIVE)`
 `   {`
 `       mPixelFormat = OF_PIXELS_NATIVE;`
 `       return true;`
 `   }`
 `   else if (pixelFormat == OF_PIXELS_RGB`
 `            || pixelFormat == OF_PIXELS_BGR`
 `            || pixelFormat == OF_PIXELS_GRAY`
 `            || pixelFormat == OF_PIXELS_I420)`
 `  {`
 `       mPixelFormat = pixelFormat;`
 `      return true;`
 `  }`
    
 `   ofLogWarning("ofxPS3EyeGrabber::setPixelFormat") << "setPixelFormat(): requested pixel format " << static_cast<short>(pixelFormat) << " not supported";`
`    return false;`
`}`

//---------------------------------------------------------------------------
ofPixelFormat RtspVideoGrabber::getPixelFormat() const {
    //note if you support more than one pixel format you will need to return a ofPixelFormat variable.
    return mPixelFormat;
}

**Comment by lewisou** [comment]
I can confirm the function videoFragmentShaderSource is not called. 

Here's my code in the main function:

`   ofGLWindowSettings settings;`
`   settings.setGLVersion(3,2);`
`   ofCreateWindow(settings); `
`   ofRunApp(new ofApp());`

**Comment by lewisou** [comment]
I finally make OSX render the video with color by hardcoding getPixelFormat to return I420 format. And the function videoFragmentShaderSource is called.

However, when I run the App on Android. The video is still grey scale.

**Comment by lewisou** [comment]
@bakercp What GLES version should I use?

I got these error messages on Android:

08-28 15:34:00.353 18294 18348 V ofShader: checkAndCreateProgram(): creating GLSL program
08-28 15:34:00.353 18294 18348 E ofShader: setupShaderFromSource(): failed creating GL_VERTEX_SHADER shader
08-28 15:34:00.353 18294 18348 V ofShader: checkAndCreateProgram(): creating GLSL program
08-28 15:34:00.353 18294 18348 E ofShader: setupShaderFromSource(): failed creating GL_FRAGMENT_SHADER shader
08-28 15:34:00.353 18294 18348 E ofShader: bindDefaults(): trying to link GLSL program, but no shaders created yet
08-28 15:34:00.353 18294 18348 E ofShader: linkProgram(): trying to link GLSL program, but no shaders created yet
08-28 15:34:00.353 18294 18348 I Adreno-UNKNOWN: <glDrawArrays:4895>: glDrawArrays is called with VERTEX_ARRAY client state disabled!

**Comment by lewisou** [comment]
@bakercp problem solved, It was a bug in OF and has been fixed on the master branch:

https://github.com/openframeworks/openFrameworks/commit/432b122fe6164aed079351d3705c8b77a29142b0

Thank you very much for your replies which drive me in the right direction.

**Comment by bakercp** [comment]
Great!
